#!/usr/bin/env bash

set -euo pipefail

SOURCE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DOCKLIGHT_BUILD_DIR=${DOCKLIGHT_BUILD_DIR:-"$SOURCE_DIR/build-release"}
RELEASE_CFLAGS=${RELEASE_CFLAGS:-"-O2 -DNDEBUG"}
RELEASE_CXXFLAGS=${RELEASE_CXXFLAGS:-"-O2 -DNDEBUG"}

if [[ $DOCKLIGHT_BUILD_DIR != /* ]]; then
    DOCKLIGHT_BUILD_DIR="$SOURCE_DIR/$DOCKLIGHT_BUILD_DIR"
fi

DOCKLIGHT_BUILD_DIR=$(realpath -m -- "$DOCKLIGHT_BUILD_DIR")

DOCKLIGHT_BUILD_DIR="$DOCKLIGHT_BUILD_DIR" "$SOURCE_DIR/clean.sh"
CFLAGS="$RELEASE_CFLAGS" \
    CXXFLAGS="$RELEASE_CXXFLAGS" \
    DOCKLIGHT_BUILD_DIR="$DOCKLIGHT_BUILD_DIR" \
    "$SOURCE_DIR/autogen.sh"
make -C "$DOCKLIGHT_BUILD_DIR" -j"$(nproc)"

printf 'Release build created at %s/src/docklight6\n' "$DOCKLIGHT_BUILD_DIR"
